export const enemiesConfig = {
  bunny: {
    name: "bunny",
    cooldown: 20000,
    speed: 100,
    texture: "bunny",
    textureType: "image",
    xpValue: 1,
    health: 10,
    damage: 10,
  },
  samu: {
    name: "samu",
    cooldown: 500,
    speed: 100,
    texture: "samu",
    textureType: "image",
    displayWidth: 30,
    xpValue: 5,
    damage: 50,
    health: 50,
  },
  joni: {
    name: "joni",
    cooldown: 2000,
    speed: 100,
    texture: "joni",
    textureType: "image",
    displayWidth: 30,
    xpValue: 10,
    damage: 100,
    health: 100,
  },
};
